package com.clipboardsync.protocol;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.Instant;

/**
 * Clipboard synchronization message exchanged over WebSocket.
 *
 * <p>The relay validates and routes this metadata, but it does not decrypt the payload.</p>
 *
 * @param type message type
 * @param updateId unique update identifier generated by the sender
 * @param sourceDeviceId stable device identifier bound to the WebSocket handshake
 * @param createdAt sender-side creation timestamp
 * @param payloadType clipboard payload type before encryption
 * @param payload encrypted clipboard payload
 */
public record ClipboardMessage(
        @NotNull MessageType type,
        @NotBlank String updateId,
        @NotBlank String sourceDeviceId,
        @NotNull Instant createdAt,
        @NotNull PayloadType payloadType,
        @Valid @NotNull EncryptedPayload payload
) {
    /**
     * Returns the message as the latest state replayed to a newly connected client.
     *
     * <p>The relay must not rewrite authenticated metadata, including {@code type}, because clients
     * use it as additional authenticated data for XChaCha20-Poly1305.</p>
     *
     * @return unchanged message suitable for replay
     */
    public ClipboardMessage asLatestStateReplay() {
        return this;
    }
}
